name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Build Image
      
    - name: Set Tag Number On the Basis Of Github_SHA
      id: tag-number
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA} | cut -c1-8)
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: harix143/sample
        tag: ${{ steps.tag-number.outputs.tag }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
 
